(function () {
  "use strict";
  const gate=document.getElementById("authGate"),loading=document.getElementById("authLoading"),panel=document.getElementById("authPanel"),form=document.getElementById("authForm"),emailInput=document.getElementById("authEmail"),submit=document.getElementById("authSubmit"),status=document.getElementById("authStatus"),application=document.getElementById("application"),accountEmail=document.getElementById("accountEmail"),signOut=document.getElementById("signOutBtn"),config=window.MINHAS_VIAGENS_CONFIG||{};
  const APP_VERSION=window.MINHAS_VIAGENS_APP_VERSION||"0.14.0"; let client=null,currentSession=null,appLoaded=false;
  window.MinhasViagensAuth={getClient:()=>client,getSession:()=>currentSession,getUser:()=>currentSession?.user||null};
  function configured(){return /^https:\/\/.+\.supabase\.co\/?$/i.test(config.supabaseUrl||"")&&Boolean(config.supabaseAnonKey)&&!/\.\.\.|placeholder|service_role/i.test(config.supabaseAnonKey);}
  function setStatus(message,type=""){status.textContent=message;status.className=`auth-status ${type}`.trim();}
  function showLogin(message="",type=""){loading.classList.add("hidden");panel.classList.remove("hidden");gate.classList.remove("hidden");application.classList.add("hidden");application.setAttribute("aria-hidden","true");accountEmail.textContent="";setStatus(message,type);}
  function displayCurrentVersion(){const brandCopy=document.querySelector(".brand p");if(brandCopy)brandCopy.textContent=brandCopy.textContent.replace(/v\d+\.\d+\.\d+/,`v${APP_VERSION}`);}
  function markStartup(stage,detail=""){document.documentElement.dataset.mvStartupStage=stage;document.documentElement.dataset.mvStartupDetail=detail;}
  function loadScript(src,attempt=0){return new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=src;script.async=false;let runtimeError=null;const expectedPath=new URL(script.src,location.href).pathname,captureRuntimeError=event=>{if(!event.filename||new URL(event.filename,location.href).pathname!==expectedPath)return;runtimeError=event.error||new Error(event.message||`Erro ao executar ${src}`);};window.addEventListener("error",captureRuntimeError);script.onload=()=>{window.removeEventListener("error",captureRuntimeError);if(runtimeError){reject(runtimeError);return;}markStartup("script-loaded",src);displayCurrentVersion();resolve();};script.onerror=()=>{window.removeEventListener("error",captureRuntimeError);script.remove();if(attempt<1){const separator=src.includes("?")?"&":"?";loadScript(`${src}${separator}retry=${Date.now()}`,attempt+1).then(resolve,reject);return;}reject(new Error(`Falha ao carregar ${src}`));};document.body.appendChild(script);});}
  async function ensureLeaflet(){if(window.L?.map)return;try{await loadScript("vendor/leaflet/leaflet.js?v=1.9.4");}catch{await loadScript("https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js");}if(!window.L?.map)throw new Error("Biblioteca do mapa indisponível");}
  async function loadAppScripts(){if(appLoaded)return;appLoaded=true;try{markStartup("checking-map");await ensureLeaflet();markStartup("loading-storage");await loadScript(`fetch-base.js?v=${APP_VERSION}`);await loadScript(`storage-pre.js?v=${APP_VERSION}`);await window.MinhasViagensStorageReady;markStartup("loading-application");const sources=["hotfix-pre.js","achievements.js","city-flags.js","route-interaction.js","route-style-lab.js","road-marker-layout.js","script.js","hotfix.js","road-threshold-hotfix.js","secondary-roads-hotfix.js","international-road-shields.js","road-marker-hotfix.js","ux-hotfix.js","endpoint-hotfix.js","city-search-fast.js","place-search-hotfix.js","edit-dialog-hotfix.js","route-click-hotfix.js","geometry-compact-hotfix.js","highway-render-hotfix.js","road-progress-core.js","road-network-hotfix.js","road-catalog-hotfix.js","sync.js","road-cloud-hotfix.js","road-sweep-hotfix.js","escape-navigation.js","iconic-routes-core.js","iconic-routes-catalog.js","iconic-route-catalog.js","iconic-routes.js","iconic-catalog-preview-hotfix.js"];for(const src of sources){await loadScript(`${src}?v=${APP_VERSION}`);if(src==="script.js"&&(!window.MinhasViagensApp||!document.querySelector(".leaflet-map-pane")))throw new Error("O núcleo do mapa não concluiu a inicialização");if(src==="iconic-route-catalog.js"&&window.MinhasViagensIconicRouteCatalogReady){markStartup("loading-iconic-catalog");const loaded=await window.MinhasViagensIconicRouteCatalogReady;if(!loaded)console.warn("Catálogo hospedado de rotas icônicas não ficou disponível no startup.");}}markStartup("ready");displayCurrentVersion();}catch(error){markStartup("failed",error?.message||String(error));console.error("Falha ao carregar o aplicativo",error);showLogin("Não foi possível carregar o aplicativo. Atualize a página e tente novamente.","error");}}
  function showApp(session){if(!session)return showLogin();currentSession=session;accountEmail.textContent=session.user?.email||"Conta conectada";gate.classList.add("hidden");application.classList.remove("hidden");application.setAttribute("aria-hidden","false");loadAppScripts();}
  function authErrorFromUrl(){const params=new URLSearchParams(window.location.search),hash=new URLSearchParams(window.location.hash.replace(/^#/,"")),description=params.get("error_description")||hash.get("error_description");if(!description)return"";history.replaceState({},document.title,location.pathname);return"O link de acesso é inválido ou expirou. Solicite um novo link.";}
  async function initialize(){const callbackError=authErrorFromUrl();if(!configured()){emailInput.disabled=true;submit.disabled=true;showLogin("Supabase ainda não configurado. Preencha Project URL e anon/public key em config.js.","error");return;}if(!window.supabase?.createClient){showLogin("Não foi possível conectar ao serviço de autenticação. Verifique sua rede e tente novamente.","error");return;}client=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});client.auth.onAuthStateChange((event,session)=>{currentSession=session||null;if(session)showApp(session);else if(event==="SIGNED_OUT"||event==="TOKEN_REFRESHED")showLogin(event==="TOKEN_REFRESHED"?"Sua sessão expirou. Solicite um novo link de acesso.":"Você saiu da sua conta.");});try{const{data,error}=await client.auth.getSession();if(error)throw error;if(data.session)showApp(data.session);else showLogin(callbackError,callbackError?"error":"");}catch{showLogin("Não foi possível verificar sua sessão. Verifique sua conexão e tente novamente.","error");}}
  form.addEventListener("submit",async event=>{event.preventDefault();const email=emailInput.value.trim();if(!email||!emailInput.checkValidity()){setStatus("Informe um endereço de e-mail válido.","error");emailInput.focus();return;}submit.disabled=true;submit.textContent="Enviando…";setStatus("Enviando link de acesso…");try{const{error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:"https://lcmsarq-creator.github.io/minhas-viagens/"}});if(error)throw error;setStatus("Enviamos um link de acesso para seu e-mail.","success");form.reset();}catch{setStatus("Não foi possível enviar o link. Verifique sua conexão e tente novamente.","error");}finally{submit.disabled=false;submit.textContent="Enviar link de acesso";}});
  signOut.addEventListener("click",async()=>{signOut.disabled=true;try{const{error}=await client.auth.signOut();if(error)throw error;currentSession=null;window.location.reload();}catch{setStatus("Não foi possível sair. Verifique sua conexão e tente novamente.","error");panel.classList.remove("hidden");gate.classList.remove("hidden");}finally{signOut.disabled=false;}});
  initialize();
})();